# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QDataMapper
                                 A QGIS plugin
 Map and refactor data from one layer to another
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-20
        copyright            : (C) 2023 by Idrostudi Srl
        email                : martinis@idrostudi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QDataMapper class from file QDataMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .q_data_mapper import QDataMapper
    return QDataMapper(iface)
